core:test:
  image: elixir:latest
  before_script:
    - make host.setup
  script:
    - make host.clean-and-test
  cache:
    paths:
      - deps
      - _build

core:cli:
  image: elixir:latest
  before_script:
    - make host.setup
  script:
    - make host.cli
  cache:
    paths:
      - deps
      - _build
  artifacts:
    paths:
      - ada

ui:build:
  image: buildpack-deps:stretch
  script:
    - cd web-ui && make --jobs=4
