mix:test:
  image: elixir:latest
  before_script:
    - make host.setup
  script:
    - make host.clean-and-test
  cache:
    paths:
      - deps
      - _build

elm:build:
  image: buildpack-deps:stretch
  script:
    - cd web-ui && make --jobs=4
