core:test:
  stage: test
  image: elixir:latest
  before_script:
    - make dev.setup
  script:
    - make host.test
  cache:
    paths:
      - deps
      - _build
  artifacts:
    reports:
      junit: ada-junit-report.xml
    paths:
      - ada-junit-report.xml

core:cli:
  stage: test
  image: elixir:latest
  before_script:
    - make dev.setup
  script:
    - make host.cli
  cache:
    paths:
      - deps
      - _build
  artifacts:
    paths:
      - ada

pages:
  stage: deploy
  image: elixir:latest
  before_script:
    - make dev.setup
  script:
    - make ci.docs
  cache:
    paths:
      - deps
      - _build
  artifacts:
    paths:
    - public
  only:
    - master
