core:test:
  stage: test
  image: elixir:latest
  before_script:
    - make host.setup
  script:
    - make host.clean-and-test
  cache:
    paths:
      - deps
      - _build

core:cli:
  stage: test
  image: elixir:latest
  before_script:
    - make host.setup
  script:
    - make host.cli
  cache:
    paths:
      - deps
      - _build
  artifacts:
    paths:
      - ada

pages:
  stage: deploy
  image: elixir:latest
  before_script:
    - make host.setup
  script:
    - make ci.docs
  cache:
    paths:
      - deps
      - _build
  artifacts:
    paths:
    - public
  only:
    - master
