mix:test:
  image: elixir:latest
  before_script:
    - mix local.rebar --force
    - mix local.hex --force
    - mix archive.install hex nerves_bootstrap --force
    - mix deps.get
  script:
    - make clean-and-test
  cache:
    paths:
      - deps
      - _build

elm:build:
  image: buildpack-deps:stretch
  script:
    - cd web-ui && make --jobs=4
