stages:
  - deps
  - test
  - deploy

core:deps:
  stage: deps
  image: elixir:latest
  script:
    - make ci.setup
  artifacts:
    paths:
      - deps
      - _build
  cache:
    paths:
      - deps
      - _build

core:test:
  stage: test
  image: elixir:latest
  dependencies:
    - core:deps
  before_script:
    - make ci.base
  script:
    - make ci.test
  cache:
    paths:
      - _build
  artifacts:
    reports:
      junit: ada-junit-report.xml
    paths:
      - ada-junit-report.xml

core:dialyzer:
  stage: test
  image: elixir:latest
  dependencies:
    - core:deps
  before_script:
    - make ci.base
  script:
    - make ci.dialyzer
  cache:
    paths:
      - priv/plts

core:cli:
  stage: test
  image: elixir:latest
  dependencies:
    - core:deps
  before_script:
    - make ci.base
  script:
    - make host.cli
  artifacts:
    paths:
      - ada

pages:
  stage: deploy
  image: elixir:latest
  dependencies:
    - core:deps
  before_script:
    - make ci.base
  script:
    - make ci.docs
  artifacts:
    paths:
    - public
  only:
    - master
