# This file is a template, and might need editing before it works on your project.
image: elixir:latest

# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-a-service

before_script:
  - mix local.rebar --force
  - mix local.hex --force
  - mix archive.install hex nerves_bootstrap --force
  - mix deps.get

mix:
  script:
    - make clean-and-test
  cache:
    paths:
      - deps
      - _build
