version: 2
jobs:
  build:
    docker:
      - image: circleci/elixir:latest
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-mix-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
            - v1-build-cache-{{ .Branch }}
            - v1-dialyzer-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
      - run: make ci.setup
      - run: make ci.test
      - store_test_results:
          path: test/mix
      - store_artifacts:
          path: test/mix
          destination: test-results
      - save_cache:
          key: v1-mix-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
          paths:
            - deps
      - save_cache:
          key: v1-build-cache-{{ .Branch }}
          paths:
            - _build
      - run: make ci.dialyzer
      - save_cache:
          key: v1-dialyzer-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
          paths:
            - priv/plts
      - run: make host.cli
      - store_artifacts:
          path: ada
          destination: cli
      - run: make ci.docs
      - store_artifacts:
          path: public
          destination: docs
