version: "3"

services:
  influx_db:
    image: influxdb:1.7.5-alpine
    container_name: ada_influx_db
    hostname: ada_influx_db
    ports:
      - 8086:8086
    networks:
      - ada
    volumes:
      - "./data/influxdb:/var/lib/influxdb"
  telegraf:
    image: telegraf:1.10.1-alpine
    container_name: ada_telegraf
    hostname: ada_telegraf
    ports:
      - 8125:8125/udp
      - 6514:6514/udp
    networks:
      - ada
    depends_on:
      - influx_db
    volumes:
      - "./config/telegraf.conf:/etc/telegraf/telegraf.conf:ro"
  chronograf:
    image: chronograf:1.7.8-alpine
    container_name: ada_chronograf
    hostname: ada_chronograf
    ports:
      - 8888:8888
    networks:
      - ada
    depends_on:
      - influx_db
      - telegraf
      - kapacitor
    command: chronograf --influxdb-url=http://ada_influx_db:8086
  kapacitor:
    image: kapacitor:1.5.2-alpine
    container_name: ada_kapacitor
    hostname: ada_kapacitor
    ports:
      - 9092:9092
    networks:
      - ada
    depends_on:
      - influx_db
    environment:
      - KAPACITOR_INFLUXDB_0_URLS_0=http://ada_influx_db:8086

networks:
  ada:
    driver: bridge
